a = int(input("Enter num1: "))
b = int(input("Enter num2: "))
print("Num a is :-",a)
print("Num b is :-",b)
print("Sum is ",a+b)
# a = input("Enter num1: ")
# b = input("Enter num2: ")
# print("Num a is :- ",a)
# print("Num b is :- ",b)
# print("Sum is ",a+b)